/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: parser.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as parser_pb from './parser_pb'; // proto import: "parser.proto"


export class XmlToJsonParserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorParse = new grpcWeb.MethodDescriptor(
    '/XmlToJsonParserService/Parse',
    grpcWeb.MethodType.UNARY,
    parser_pb.ParseRequest,
    parser_pb.ParseResponse,
    (request: parser_pb.ParseRequest) => {
      return request.serializeBinary();
    },
    parser_pb.ParseResponse.deserializeBinary
  );

  parse(
    request: parser_pb.ParseRequest,
    metadata?: grpcWeb.Metadata | null): Promise<parser_pb.ParseResponse>;

  parse(
    request: parser_pb.ParseRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: parser_pb.ParseResponse) => void): grpcWeb.ClientReadableStream<parser_pb.ParseResponse>;

  parse(
    request: parser_pb.ParseRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: parser_pb.ParseResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/XmlToJsonParserService/Parse',
        request,
        metadata || {},
        this.methodDescriptorParse,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/XmlToJsonParserService/Parse',
    request,
    metadata || {},
    this.methodDescriptorParse);
  }

}

